package property

const (
	MapName            = "name"
	MapClass           = "class"
	MapColumns         = "columns"
	MapRows            = "rows"
	MapTileWidth       = "tileWidth"
	MapTileHeight      = "tileHeight"
	MapParallaxX       = "parallaxX"
	MapParallaxY       = "parallaxY"
	MapInfinite        = "infinite"
	MapBackgroundColor = "backgroundColor"
	MapWorldX          = "worldX"
	MapWorldY          = "worldY"

	TilesetName       = "name"
	TilesetClass      = "class"
	TilesetTileWidth  = "width"
	TilesetTileHeight = "height"
	TilesetColumns    = "columns"
	TilesetRows       = "rows"
	TilesetSpacing    = "spacing"
	TilesetOffsetX    = "offsetX"
	TilesetOffsetY    = "offsetY"
	TilesetAtlasId    = "atlasId"
	TilesetRenderSize = "renderSize"
	TilesetFillMode   = "fillMode"

	TileId          = "id"
	TileClass       = "class"
	TileWidth       = "width"
	TileHeight      = "height"
	TileProbability = "probability"
	TileImage       = "image"

	LayerId        = "id"
	LayerName      = "name"
	LayerClass     = "class"
	LayerVisible   = "visible"
	LayerLocked    = "locked"
	LayerOpacity   = "opacity"
	LayerTint      = "tint"
	LayerOffsetX   = "offsetX"
	LayerOffsetY   = "offsetY"
	LayerParallaxX = "parallaxX"
	LayerParallaxY = "parallaxY"
	LayerOrder     = "order"

	LayerColor     = "color"
	LayerDrawOrder = "drawOrder"

	LayerImage            = "image"
	LayerImageWidth       = "imageWidth"
	LayerImageHeight      = "imageHeight"
	LayerTransparentColor = "transparentColor"
	LayerRepeatX          = "repeatX"
	LayerRepeatY          = "repeatY"

	ObjectId       = "id"
	ObjectName     = "name"
	ObjectTemplate = "template"
	ObjectClass    = "class"
	ObjectVisible  = "visible"
	ObjectLocked   = "locked"
	ObjectX        = "x"
	ObjectY        = "y"
	ObjectWidth    = "width"
	ObjectHeight   = "height"
	ObjectRotation = "rotation"
	ObjectType     = "type"
	ObjectOrder    = "order"

	ObjectTileId = "tileId"
	ObjectFlipX  = "flipX"
	ObjectFlipY  = "flipY"

	ObjectText          = "text"
	ObjectTextFont      = "font"
	ObjectTextFontSize  = "fontSize"
	ObjectTextAlignX    = "alignX"
	ObjectTextAlignY    = "alignY"
	ObjectTextWordWrap  = "wordWrap"
	ObjectTextColor     = "color"
	ObjectTextBold      = "bold"
	ObjectTextItalic    = "italic"
	ObjectTextStrikeout = "strikeout"
	ObjectTextUnderline = "underline"
)
