package property

const (
	MapName            = "name"
	MapClass           = "class"
	MapColumns         = "columns"
	MapRows            = "rows"
	MapTileWidth       = "tileWidth"
	MapTileHeight      = "tileHeight"
	MapParallaxX       = "parallaxX"
	MapParallaxY       = "parallaxY"
	MapInfinite        = "infinite"
	MapBackgroundColor = "backgroundColor"
	MapWorldX          = "worldX"
	MapWorldY          = "worldY"

	TilesetName       = "name"
	TilesetClass      = "class"
	TilesetTileWidth  = "width"
	TilesetTileHeight = "height"
	TilesetColumns    = "columns"
	TilesetRows       = "rows"
	TilesetSpacing    = "spacing"
	TilesetOffsetX    = "offsetX"
	TilesetOffsetY    = "offsetY"
	TilesetAtlasId    = "atlasId"

	TileId          = "id"
	TileClass       = "class"
	TileWidth       = "width"
	TileHeight      = "height"
	TileProbability = "probability"

	LayerName      = "name"
	LayerClass     = "class"
	LayerVisible   = "visible"
	LayerLocked    = "locked"
	LayerOpacity   = "opacity"
	LayerTint      = "tint"
	LayerOffsetX   = "offsetX"
	LayerOffsetY   = "offsetY"
	LayerParallaxX = "parallaxX"
	LayerParallaxY = "parallaxY"

	LayerColor     = "color"
	LayerDrawOrder = "drawOrder"

	LayerImage            = "image"
	LayerTransparentColor = "transparentColor"
	LayerRepeatX          = "repeatX"
	LayerRepeatY          = "repeatY"
	LayerWidth            = "width"
	LayerHeight           = "height"

	ObjectId       = "id"
	ObjectName     = "name"
	ObjectTemplate = "template"
	ObjectClass    = "class"
	ObjectVisible  = "visible"
	ObjectLocked   = "locked"
	ObjectX        = "x"
	ObjectY        = "y"
	ObjectWidth    = "width"
	ObjectHeight   = "height"
	ObjectRotation = "rotation"
	ObjectTileId   = "tileId"
	ObjectFlipX    = "flipX"
	ObjectFlipY    = "flipY"
)
