package property

const (
	MapName            = "name"
	MapClass           = "class"
	MapColumns         = "columns"
	MapRows            = "rows"
	MapTileWidth       = "tileWidth"
	MapTileHeight      = "tileHeight"
	MapParallaxX       = "parallaxX"
	MapParallaxY       = "parallaxY"
	MapInfinite        = "infinite"
	MapBackgroundColor = "backgroundColor"

	TilesetName       = "name"
	TilesetClass      = "class"
	TilesetTileWidth  = "width"
	TilesetTileHeight = "height"
	TilesetTileCount  = "count"
	TilesetColumns    = "columns"
	TilesetSpacing    = "spacing"
	TilesetOffsetX    = "offsetX"
	TilesetOffsetY    = "offsetY"
	TilesetAtlasId    = "atlasId"

	LayerName      = "name"
	LayerClass     = "class"
	LayerVisible   = "visible"
	LayerLocked    = "locked"
	LayerOpacity   = "opacity"
	LayerTint      = "tint"
	LayerOffsetX   = "offsetX"
	LayerOffsetY   = "offsetY"
	LayerParallaxX = "parallaxX"
	LayerParallaxY = "parallaxY"

	LayerColor     = "color"
	LayerDrawOrder = "drawOrder"

	LayerImage            = "image"
	LayerTransparentColor = "transparentColor"
	LayerRepeatX          = "repeatX"
	LayerRepeatY          = "repeatY"
	LayerWidth            = "width"
	LayerHeight           = "height"
)
